AWSTemplateFormatVersion: 2010-09-09

Description: |
  This template creates a single EC2 instance. Hosting static web page run on Apache web server.

Parameters:
  KeyPairName:
    Type: String
    Description: Name of the existing EC2 Key Pair
    Default: rafe-lesson # Provide a default value or remove it if you want users to always specify a key pair name

  SecurityGroupName:
    Type: String
    Description: Name of the existing Security Group
    Default: rafe-ssh-http # Provide a default value or remove it if you want users to always specify a security group name

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05c13eab67c5d8861
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SecurityGroups: 
        - !Ref SecurityGroupName
      Tags:
        - Key: Name
          Value: rafe-lesson-cloudformation
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install git -y
          yum install python3-pip -y
          pip install -r requirements.txt
          git clone https://github.com/bluehackrafestefano/MyFlaskProj1.git app
          cd app
          python3 app-with-sqlite.py

Outputs:
  WebsiteURL:
    Description: Roman Numerals
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt EC2Instance.PublicIp